name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  push_to_registry:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo 
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
    - uses: docker/login-action@v2
    - with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push the Docker image
    - uses: docker/build-push-action@v4
    - with:
        #context: DockerfileFolder/
        push: true
        tags: joel033/githubActionpush:latest
        
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
